[package]
name = "thrigger_support"
version = "0.2.0"
authors = ["Thrigger <21341498+Thrigger@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
